### ISSUE TITLE
Additional information about the DSP uCode files

### ISSUE THREAD

**Issue by Bamboo5838** [enekochan/insta360-go2-firmware-tool#1]
Hi, I'm sorry if this question is in the wrong place.
I was wondering if someone could point me in a direction to find out more about the files orccode.bin, orcme.bin and default_binary.bin that are described in the docs about firmware structure, since I encountered them in the software of an IP Cam, but could not find any information about them. Thanks in advance

**Comment by enekochan** [comment]
Those are most probably the executable codes for video, audio and photo capture from the image sensor and microphone. By the name of the files may be are Optimized Inner Loops Runtime Compiler generated code.

```
Orc is a library and set of tools for compiling and executing
very simple programs that operate on arrays of data.  The "language"
is a generic assembly language that represents many of the features
available in SIMD architectures, including saturated addition and
subtraction, and many arithmetic operations.
```

From : https://github.com/GStreamer/orc
