### ISSUE TITLE
how to create a file while connected with telnet

### ISSUE THREAD

**Issue by dan9thsense** [enekochan/insta360-go2-firmware-tool#3]
When I connected over telnet and tried to create a bootup.sh file using vi, it says the file system is read only and will not save the file.

**Comment by enekochan** [comment]
Make sure you are opening `/tmp/SD0/bootup.sh`. That file is contained in the flash memory of the camera so you can also create and edit connecting the camera with USB to the computer as any flash drive.

The rest of the system is read only.

**Comment by dan9thsense** [comment]
Thank you for your reply. When I try to write into the /tmp/SD0 folder, the response is "No such device" regardless of the filename.  I think that is better than a read-only file system, but I am still unable to  create a bootup.sh file.

This is on an X2. On an X3 I am unable to telnet because it requires a password and I cannot figure out the password.

**Comment by dan9thsense** [comment]
I did put bootup.sh onto the flash memory card (in a tmp/SD0 folder I created there) and it does show up when using telnet. However, as far as I can tell, the script didn't run.
Here is the script; no bootup.log file shows up in tmp/SD0 after reboot.

#!/usr/bin/env sh

date > bootup.log

**Comment by enekochan** [comment]
But this is for the Go 2 and Go 3. I don't know about X2.

**Comment by dan9thsense** [comment]
I understand and hoped it would apply to the X2 and X3 (most of what you documented does work with those cameras). Very much appreciate the help you provided.
